language: php

php:
  - 7.3.16

before_script:
  - cp .env.travis .env
  - composer self-update --snapshot
  - composer install --no-interaction

script:
  - touch database/database.sqlite
  - php artisan key:generate
  - vendor/bin/phpunit

services:
  - redis-server

cache:
  directories:
    - vendor